route:
    receiver: 'slack'
 
receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'PROMETHEUS'
            channel: '#prometheus'
            api_url: 'https://APISLACK'
