global:
  scrape_interval:    10s
  evaluation_interval: 20s
rule_files:
 - 'rules/alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
         - targets: ['172.17.0.2:9093']

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'nameserver'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
         - targets: ['server.address']

